# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               strive.space
tagline:             'effort'
description:         'blogging the strive'
url:                 strive.space
baseurl:             ''
gems: [jekyll-paginate]
paginate:            5
paginate_path: "page:num"

# About/contact
author:
  name:              brendanmcfarland
  url:               https://twitter.com/brendanmcfarlan
  email:             brendanm@gmail.com

# Custom vars
version:             1.0.0
